### ISSUE TITLE
Citation needed: reproducibility of container results

### ISSUE THREAD

**Issue by johnflavin** [boutiques/boutiques-paper#1]
I think this sentence in the introduction requires a citation:
> Meanwhile, virtual container systems such as Docker and Singularity... improve the reproducibility of analyses by defining immutable, reusable execution environments.

Has it been demonstrated (and published) that one can run the same analysis in a container on different machine architectures and achieve the same numerical results? You yourself know very well that if you run the same analyses on different architechtures *without* using containers, [you get different numerical results](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4408913/). Has the test in that paper been run using containers, and were the results reproducible? (I should say that I have been thinking of running that test myself, because that reproducibility is one of the selling points of using containers for processing on our various platforms. I'm not aware that it has yet been shown to be true, but maybe someone has done this.)

I suppose a counter-argument is that the sentence as written is fine and needs no citation because "improve the reproducibility of analyses" does not have to mean "make analyses numerically consistent across architectures". Maybe you still have to use the same architecture to get the same results, but using containers just makes it easier to get a reproduction off the ground. That alone could justify the words "improve the reproducibility of analyses".

**Comment by glatard** [comment]
Containers clearly aren't sufficient to guarantee numerical reproducibility as they are useless to prevent hardware differences. I once had a container where some code was crashing on AMD after being compiled on Intel with arch-specific flags. Moreover, freezing the execution environment doesn't seem to me like the best answer to numerical reproducibility issues since this is only a workaround to the problem.

However, as you noted, this sentence is quite general and not focused on numerical differences which are only a small part of the whole reproducibility picture. Yes, I do believe that containers are useful to help people re-use software over time and across different platforms. I wouldn't bother discussing all this in the introduction, but it would be interesting to have a paragraph on it in the discussion indeed. Thanks for the suggestion!

**Comment by glatard** [comment]
See discussion paragraph added in #94800eb
